### ISSUE TITLE
Native UI for imports and JSON bundles...

### ISSUE THREAD

**Issue by twMat** [OokTech/TW5-FederationCore#6]
Not an "issue" as much as a note apropos you making "another unpacking function that makes preview tiddlers";

When using the *native* TW import mechanism on a JSON tiddler, the user is presented with a checkbox-list for the titles to allow picking which exact tiddlers to unpack.

![image](https://user-images.githubusercontent.com/4534056/61791650-e40dc080-ae1a-11e9-8874-ab1f425a8422.png)

It would make sense to reuse this mechanism and UI.  Note that it features a "preview" function!

Futher, I'm starting to doubt what the point with the special bundle format is, i.e why not only stick with JSON and native mechanisms for this? The *single* advantage I can see with the special format is readability. Am I missing something? Just maybe the whole bundling should be in JSON.

**Comment by twMat** [comment]
A desirable side effect *might* be that this encourages people develop more tools for manipulating JSON tids which is overall lacking in TW :-)

**Comment by inmysocks** [comment]
Using the import mechanism is already supported, I just never added it to the readme.

Put $useImport=true in the action widget when unbundling tiddlers.

The tiddler format is for readability and because everyone said that json was confusing and too complex during the testing previously.

**Comment by AnthonyMuscio** [comment]
See also https://groups.google.com/forum/?hl=en#!topic/tiddlywikidev/rpTa2RqYO-g

I am progressing the import and pack process as we speak.

Regards
Tony

**Comment by AnthonyMuscio** [comment]
I would like to provide a link to an action widget be it a wiki, a stand alone json or .tis file, or a tiddler in JSON format within a wiki (with the permalink) such that when the action is triggered such as via a button or startup action it will optional trigger the above import mechanism, a modified version of it OR import silently with or without overwrites. 

I would also like to do this with text files as well, so I can query an external server state.

This should be possible with simple mods, I just do no know how yet.

**Comment by inmysocks** [comment]
While this is a productive discussion, this isn't the place for it.

Please put things that would extend beyond the federation core into the https://github.com/OokTech/TW5-FederationExtended repository. Now that that repository exists please limit this one to issues and discussion that are specifically about the FederationCore plugin.
